{:genres=>["Animation", "Family"], :title=>"Don't Let the Pigeon Drive the Bus!", :overview=>"Collect the entire library of Scholastic Storybook Treasures and read along on screen with your favorite classic children’s stories, brought vividly to life on DVD.  DON’T LET THE PIGEON DRIVE THE BUS (Written and illustrated by Mo Willems, narrated by Mo Willems and Jon Scieszka) When a bus driver takes a break, a very unlikely volunteer springs up – a pigeon! Will you let him drive?  KNUFFLE BUNNY: A CAUTIONARY TALE (Written and illustrated by Mo Willems, narrated by Mo Willems and Trixie) Trixie, Daddy and Knuffle Bunny go on an exciting trip to the laundromat. Suddenly, their adventure takes a surprising turn when Trixie realizes that something is missing!  LEONARDO, THE TERRIBLE MONSTER (Written, illustrated, and narrated by Mo Willems) Leonardo is a terrible monster – he can’t seem to frighten anyone! He comes up with a plan to find the perfect little boy and scare the tuna salad out of him. Will he succeed?  Supports Cooperation; Early Reading; Problem Solving", :poster_path=>"https://image.tmdb.org/t/p/w185/yeejmLw1ZaCc6L5zKxPHHsMHAxU.jpg", :release_date=>"2010-09-28"}
{:genres=>[], :title=>"Homework", :overview=>"A freestyle snowboard movie from KBR Productions.", :poster_path=>"https://image.tmdb.org/t/p/w185/pnA7oqpvygHsotmgOud6j0eaGU9.jpg", :release_date=>"2010-11-12"}
{:genres=>[], :title=>"Ayumi Hamasaki Arena Tour 2009 A: Next Level", :overview=>"Ayumi Hamasaki Arena Tour 2009 A: Next Level is the twelfth concert tour DVD by the Japanese pop singer Ayumi Hamasaki. It was released on the April 14, 2010, the same day of the release of Rock 'n' Roll Circus. On the Oricon weekly chart, it peaked at second place and is currently still charting. The tour was a major sell out across Japan, spanning over 32 shows across the country. The tour broke attendance records, playing to 400,000 fans across Japan.", :poster_path=>"https://image.tmdb.org/t/p/w185/uwGTQWnctwG8u5JHfq9WhOUzQMb.jpg", :release_date=>"2010-08-28"}
{:genres=>[], :title=>"Swing", :overview=>"In the wake of a fight at school, an eight-year-old boy deals with the death of a classmate.", :poster_path=>"https://image.tmdb.org/t/p/w185/qUa7u0Kkb4Bin9FfEiQzBaWsalf.jpg", :release_date=>"2010-03-02"}
{:genres=>["Fantasy", "Family"], :title=>"Aschenputtel", :overview=>"", :poster_path=>"https://image.tmdb.org/t/p/w185/1OuDCLuebtFJNrE0M4xTcCQ938l.jpg", :release_date=>"2010-12-24"}
{:genres=>[], :title=>"Utopia e Barbárie", :overview=>"", :poster_path=>"https://image.tmdb.org/t/p/w185/56Z3Gs6AzU9OLEF2UBiRVCv9hZU.jpg", :release_date=>"2010-01-10"}
{:genres=>[], :title=>"When it Will Be Silent", :overview=>"In the aftermath of an apocalypse, a mans tragic loss leads him to an unequivocal decision.", :poster_path=>"https://image.tmdb.org/t/p/w185/bJPharWO8n6P2EF2RcA6oVgYeuY.jpg", :release_date=>"2010-06-25"}
{:genres=>[], :title=>"The Last Christmas", :overview=>"Resort manager Claire prepares for a holiday family reunion, but when her grandfather makes a startling announcement and then dies unexpectedly, Claire must solve a devilishly clever puzzle in order to earn her inheritance and expose a murderer.", :poster_path=>"https://image.tmdb.org/t/p/w185/1Y0KCdVSpkHhuw1in5oefAGyLsJ.jpg", :release_date=>"2010-12-11"}
{:genres=>[], :title=>"The Fairy Queen", :overview=>"Jonathan Kent's spectacular production of Purcell's huge semi-opera is joyous, imaginative and witty.  Glyndebourne, with its intimate auditorium, provides the perfect setting for the drama which is partly spoken and partly sun.  Based on an adaptation of Shakespeare's A Midsummer Night's Dream,", :poster_path=>"https://image.tmdb.org/t/p/w185/d7kQ0C4ETwotRgIWi9sFfl246MK.jpg", :release_date=>"2010-06-29"}
{:genres=>[], :title=>"Stephen K Amos - The Feel Good Factor", :overview=>"Stephen K Amos is guaranteed to provide you with the feel good factor in this laugh a minute stand-up performance filmed in front of a sell-out audience at the Hammersmith Apollo.\r Star of Montreal, Melbourne and Edinburgh festivals, Amos is a hit with critics and audiences alike and has a swagger of awards in tow. In fact he's so flipping good he's only gone and got his very own BBC show called, you guessed it The Stephen K Amos Show.", :poster_path=>"https://image.tmdb.org/t/p/w185/1DRZxao3ytKDlzV4ESnUVJtixvX.jpg", :release_date=>"2010-01-01"}
{:genres=>[], :title=>"Hope for Haiti", :overview=>"Telethon concert in support of relief organizations dedicated to assisting victims of the earthquake that struck Haiti on 12 January 2010.", :poster_path=>"https://image.tmdb.org/t/p/w185/xXCGeNgOsX35pWO19npIkcE1pBQ.jpg", :release_date=>"2010-01-02"}
{:genres=>["Documentary", "Music"], :title=>"Napozz Holddal - A Kispálfilm", :overview=>"With an intimate look into the band's life, this concert documentary is about the farewell concert of cult Hungarian band 'Kispál és a borz'.", :poster_path=>"https://image.tmdb.org/t/p/w185/cuo5zu0KMT8OfHsjzzeJwscvnWn.jpg", :release_date=>"2010-12-14"}
{:genres=>[], :title=>"Elektra", :overview=>"The Nikolaus Lehnhoff production of Richard Strauss's \"Elektra\", recorded live at the Salzburger Festspiele in 2010. Iréne Theorin stars as Elektra, with Eva-Maria Westbroek as Chrysothemis, Waltraud Meier as Klytämnestra, Robert Gambill as Aegisth, and René Pape as Orest. Daniele Gatti conducts the Wiener Philharmoniker.", :poster_path=>"https://image.tmdb.org/t/p/w185/4DEgN2Ztg1uIGcNJywOdPCTcnXz.jpg", :release_date=>"2010-08-01"}
{:genres=>[], :title=>"Out", :overview=>"A boy wants to go outside, but his mother won't let him.", :poster_path=>"https://image.tmdb.org/t/p/w185/2aCSVdkvwZOml0RZgEkcgTSa716.jpg", :release_date=>"2010-10-01"}
{:genres=>["Documentary"], :title=>"Up Against the Wall", :overview=>"A critical look at Norwegian fur production. The documentary follows a group of activists that in 2010 documented horrible conditions in Norwegian fur farms for the third consecutive year.", :poster_path=>"https://image.tmdb.org/t/p/w185", :release_date=>"2010-10-31"}
{:genres=>[], :title=>"Hello Kitty - L'anniversaire surprise", :overview=>"", :poster_path=>"https://image.tmdb.org/t/p/w185/zeREPqeAfF4V3k1cXba1LEUOGNj.jpg", :release_date=>"2010-09-21"}
{:genres=>[], :title=>"Shaun das Schaf - Das Hüpfschaf", :overview=>"", :poster_path=>"https://image.tmdb.org/t/p/w185/o6ezv6vIR5OxtfKnWm1aH7GxpWI.jpg", :release_date=>"2010-02-04"}
{:genres=>[], :title=>"Shaun das Schaf - Frisch verliebt", :overview=>"", :poster_path=>"https://image.tmdb.org/t/p/w185/baYdQNHsvXsW2jq6i19DIYGCAlk.jpg", :release_date=>"2010-04-08"}
{:genres=>[], :title=>"Shaun das Schaf - Der Triller-Pfeifer", :overview=>"", :poster_path=>"https://image.tmdb.org/t/p/w185/uUzjpQvfkjAFHITtSlrT0OauDCn.jpg", :release_date=>"2010-08-19"}
{:genres=>[], :title=>"Shaun das Schaf - Raserei", :overview=>"", :poster_path=>"https://image.tmdb.org/t/p/w185/4bBsZybfs80gwZYB4vFtwpE9Ihz.jpg", :release_date=>"2010-10-07"}
{:genres=>["Drama", "Adventure"], :title=>"The Revenant", :overview=>"In the 1820s, a frontiersman, Hugh Glass, sets out on a path of vengeance against those who left him for dead after a bear mauling.", :poster_path=>"https://image.tmdb.org/t/p/w185/oXUWEc5i3wYyFnL1Ycu8ppxxPvs.jpg", :release_date=>"2015-12-25"}
{:genres=>["Western"], :title=>"The Hateful Eight", :overview=>"Bounty hunters seek shelter from a raging blizzard and get caught up in a plot of betrayal and deception.", :poster_path=>"https://image.tmdb.org/t/p/w185/fqe8JxDNO8B8QfOGTdjh6sPCdSC.jpg", :release_date=>"2015-12-25"}
{:genres=>["Mystery", "Thriller", "Science Fiction"], :title=>"400 Days", :overview=>"4 would be astronauts spend 400 days in a land locked space simulator to test the psychological effects of deep space travel but, when something goes terribly wrong and they are forced to leave the simulation, they discover that everything on earth has changed. Is this real or is the simulation on a higher level than they could have ever imagined?", :poster_path=>"https://image.tmdb.org/t/p/w185/vVFmAOLPpwgxpxBkXAbMWD6qYl5.jpg", :release_date=>"2016-01-12"}
{:genres=>["Crime", "Action"], :title=>"Close Range", :overview=>"A rogue soldier turned outlaw is thrust into a relentless fight with a corrupt sheriff, his obedient deputies, and a dangerous drug cartel in order to protect his sister and her young daughter.", :poster_path=>"https://image.tmdb.org/t/p/w185/8529WGZSg0LRoiKMnOe1XrQ1oPR.jpg", :release_date=>"2015-12-31"}
{:genres=>["Crime", "Action", "Thriller"], :title=>"Point Break", :overview=>"A young undercover FBI agent infiltrates a gang of thieves who share a common interest in extreme sports. A remake of the 1991 film, \"Point Break\".", :poster_path=>"https://image.tmdb.org/t/p/w185/4zfbf70df2ySChbsIEjhAC9oXJ1.jpg", :release_date=>"2015-12-25"}
{:genres=>["Drama"], :title=>"45 Years", :overview=>"There is just one week until Kate Mercer's 45th wedding anniversary and the planning for the party is going well. But then a letter arrives for her husband. The body of his first love has been discovered, frozen and preserved in the icy glaciers of the Swiss Alps. By the time the party is upon them, five days later, there may not be a marriage left to celebrate.", :poster_path=>"https://image.tmdb.org/t/p/w185/x3jVnPRpoWHVW3orDWYUOPxno6F.jpg", :release_date=>"2015-12-23"}
{:genres=>["Comedy"], :title=>"Daddy's Home", :overview=>"The story of a mild-mannered radio executive (Ferrell) who strives to become the best stepdad ever to his wife's two children, but complications ensue when their freewheeling, freeloading real father arrives, forcing stepdad to compete for the affection of the kids.", :poster_path=>"https://image.tmdb.org/t/p/w185/eIs0TmwMZRrSAbMgLWr4hlztaUZ.jpg", :release_date=>"2015-12-25"}
{:genres=>["Comedy", "Drama"], :title=>"Joy", :overview=>"A story based on the life of a struggling Long Island single mom who became one of the country's most successful entrepreneurs.", :poster_path=>"https://image.tmdb.org/t/p/w185/tnpsyUfyK0PZTqbke4JYlSkA3U0.jpg", :release_date=>"2015-12-25"}
{:genres=>["Action"], :title=>"Ip Man 3", :overview=>"At the end of the 1950's, finally settled into a stable life, during his daily trip to take his young son to and from school, Ip Man meets another father Cheung Tin-chi; it so happens that Cheung is a fellow Wing Chun practitioner.  Through their infrequent contact, the two fathers develop an interesting relationship. Unexpectedly, gangsters led by Sang are trying to take over properties in the neighbourhood and Ip Man decides to lead his students to guard the neighbourhood!  Ip Man's conflict with the gangsters becomes heated and he discovers that the boss behind the takeover is the foreigner Frank.  Because Frank colludes with an English police superintendent, even the police inspector Fat Ball cannot do much to help.  Undeterred, Ip Man stays to guard the neighbourhood.", :poster_path=>"https://image.tmdb.org/t/p/w185/enp1pSLoPdcWss2zEkwfP4Eek46.jpg", :release_date=>"2015-12-25"}
{:genres=>["Romance"], :title=>"Palmeras en la nieve", :overview=>"", :poster_path=>"https://image.tmdb.org/t/p/w185/cJcPHjhgBZqpUN5F9J6tashN0Pq.jpg", :release_date=>"2015-12-25"}
{:genres=>["Drama"], :title=>"Concussion", :overview=>"A look at how American football players suffer from major head injuries and life-long debilitating problems as a result of repeated concussions and efforts by the National Football League to deny it.", :poster_path=>"https://image.tmdb.org/t/p/w185/vdK1f9kpY5QEwrAiXs9R7PlerNC.jpg", :release_date=>"2015-12-25"}
{:genres=>[], :title=>"Charlie", :overview=>"Charlie is an upcoming Malayalam film directed, co-written and co-produced by Martin Prakkat. It stars Dulquer Salmaan, Parvathy and Aparna Gopinath. The music is composed by Gopi Sundar, while Jomon T. John handles the cinematography", :poster_path=>"https://image.tmdb.org/t/p/w185/kj6t9f1P28H3M6boJafw4TAOL9e.jpg", :release_date=>"2015-12-24"}
{:genres=>["Science Fiction"], :title=>"The Prototype", :overview=>"The military tries to track down a humanoid drone that escapes from a government facility.", :poster_path=>"https://image.tmdb.org/t/p/w185/t8SkI1o5T9iIPvZezrBJFhCyEt9.jpg", :release_date=>"2015-12-31"}
{:genres=>["Comedy"], :title=>"Le Nouveau", :overview=>"Benoit is the new kid at a junior high school. He's bullied by a gang of arrogant boys who make things difficult for him. Determined not to be pushed around, Benoit organizes a big party and invites the whole class. But on the night of the party, only three students turn up...", :poster_path=>"https://image.tmdb.org/t/p/w185/eSYNESUP4BOtfVoHjjLR1xt3M8P.jpg", :release_date=>"2015-12-23"}
{:genres=>["Fantasy", "Animation", "Comedy"], :title=>"Anomalisa", :overview=>"Michael, a famous motivational speaker, copes with life's disappointments. His life changes when he meets Lisa.", :poster_path=>"https://image.tmdb.org/t/p/w185/h6orfYDihFwZfneMvXyGUeTufeK.jpg", :release_date=>"2015-12-30"}
{:genres=>["Romance", "Drama"], :title=>"Other People's Children", :overview=>"A filmmaker, reeling from the death of her famous father, falls down the rabbit hole of a charismatic homeless man who becomes the subject of her latest documentary and her new love interest.", :poster_path=>"https://image.tmdb.org/t/p/w185/nU9hzNlYPAhm3p5FAcl07OkeK1B.jpg", :release_date=>"2015-12-25"}
{:genres=>["Drama"], :title=>"Mountains May Depart", :overview=>"Jia’s first feature shot outside his native China is a generations-spanning drama that unfolds in three parts, set in the 1990s, the present day and 2025, respectively.", :poster_path=>"https://image.tmdb.org/t/p/w185/zBA6lO2pdR85qbB4KAVDGRLBPkc.jpg", :release_date=>"2015-12-23"}
{:genres=>["Comedy", "Drama"], :title=>"A Man Called Ove", :overview=>"59 year-old Ove is the block’s grumpy man. Several years ago he was deposed as president of the condominium association, but he could not give a damn about being deposed and therefore keeps looking over the neighborhood with an iron fist. When pregnant Parvaneh and her family move into the terraced house opposite Ove and accidentally back into Ove’s mailbox it sets off the beginning of an unexpected friendship.", :poster_path=>"https://image.tmdb.org/t/p/w185/cetB5fs6tHY1H33e94WHeU92etV.jpg", :release_date=>"2015-12-25"}
{:genres=>["Action", "Comedy"], :title=>"Skiptrace", :overview=>"A detective from Hong Kong teams up with an American gambler to battle against a notorious Chinese criminal.", :poster_path=>"https://image.tmdb.org/t/p/w185", :release_date=>"2015-12-24"}
{:genres=>["Fantasy", "Drama", "Family"], :title=>"Yellow Day", :overview=>"Yellow Day chronicles a young man's life-changing and inspirational journey through the mysterious Yellow Day. To many, the Yellow Day is simply a fun day celebrating outreach at a kid's camp, but to some, God bestows visions and miracles, transforming their lives. For this young man, the Yellow Day becomes an imaginative adventure: showing him true heroes, challenging him to face his fears, find love, and inviting him to accept grace, so that he can be shaped into who he is meant to be.", :poster_path=>"https://image.tmdb.org/t/p/w185/wXLrKag5KCzSSVgIRuCBv4PeKHK.jpg", :release_date=>"2015-12-25"}
{:genres=>["Music", "Drama"], :title=>"Whiplash", :overview=>"Under the direction of a ruthless instructor, a talented young drummer begins to pursue perfection at any cost, even his humanity.", :poster_path=>"https://image.tmdb.org/t/p/w185/lIv1QinFqz4dlp5U4lQ6HaiskOZ.jpg", :release_date=>"2014-10-10"}
{:genres=>["Crime", "Drama", "Thriller"], :title=>"Victoria", :overview=>"A young Spanish woman who has newly moved to Berlin finds her flirtation with a local guy turn potentially deadly as their night out with his friends reveals a dangerous secret.", :poster_path=>"https://image.tmdb.org/t/p/w185/t66eAg7xBLGoSSoA8JtJtX3NKs1.jpg", :release_date=>"2015-06-11"}
{:genres=>["Drama", "Science Fiction"], :title=>"Interstellar", :overview=>"Interstellar chronicles the adventures of a group of explorers who make use of a newly discovered wormhole to surpass the limitations on human space travel and conquer the vast distances involved in an interstellar voyage.", :poster_path=>"https://image.tmdb.org/t/p/w185/nBNZadXqJSdt05SHLqgT0HuC5Gm.jpg", :release_date=>"2014-11-05"}
{:genres=>["Drama", "Crime"], :title=>"The Shawshank Redemption", :overview=>"Framed in the 1940s for the double murder of his wife and her lover, upstanding banker Andy Dufresne begins a new life at the Shawshank prison, where he puts his accounting skills to work for an amoral warden. During his long stretch in prison, Dufresne comes to be admired by the other inmates -- including an older prisoner named Red -- for his integrity and unquenchable sense of hope.", :poster_path=>"https://image.tmdb.org/t/p/w185/9O7gLzmreU0nGkIB6K3BsJbzvNv.jpg", :release_date=>"1994-09-14"}
{:genres=>["Animation", "Family"], :title=>"Presto", :overview=>"Dignity. Poise. Mystery. We expect nothing less from the great turn-of-the-century magician, Presto. But when Presto neglects to feed his rabbit one too many times, the magician finds he isn't the only one with a few tricks up his sleeve!", :poster_path=>"https://image.tmdb.org/t/p/w185/A2rxR8g3y6kcjIoR2fcwtq9eppc.jpg", :release_date=>"2008-06-26"}
{:genres=>["Animation", "Romance", "Family"], :title=>"Paperman", :overview=>"An urban office worker finds that paper airplanes are instrumental in meeting a girl in ways he never expected.", :poster_path=>"https://image.tmdb.org/t/p/w185/3TpMBcAYH4cxCw5WoRacWodMTCG.jpg", :release_date=>"2012-11-02"}
{:genres=>["Drama", "Crime"], :title=>"The Godfather", :overview=>"The story spans the years from 1945 to 1955 and chronicles the fictional Italian-American Corleone crime family. When organized crime family patriarch Vito Corleone barely survives an attempt on his life, his youngest son, Michael, steps in to take care of the would-be killers, launching a campaign of bloody revenge.", :poster_path=>"https://image.tmdb.org/t/p/w185/d4KNaTrltq6bpkFS01pYtyXa09m.jpg", :release_date=>"1972-03-15"}
{:genres=>["Romance", "Comedy", "Animation", "Drama", "Family"], :title=>"Feast", :overview=>"This Oscar-winning animated short film tells the story of one man's love life is seen through the eyes of his best friend and dog, Winston, and revealed bite by bite through the meals they share.", :poster_path=>"https://image.tmdb.org/t/p/w185/qJ9ouIj4wN24asvKTUSAcJnSfrT.jpg", :release_date=>"2014-11-07"}
{:genres=>["Drama", "Comedy"], :title=>"The Intouchables", :overview=>"A true story of two men who should never have met - a quadriplegic aristocrat who was injured in a paragliding accident and a young man from the projects.", :poster_path=>"https://image.tmdb.org/t/p/w185/4mFsNQwbD0F237Tx7gAPotd0nbJ.jpg", :release_date=>"2011-11-02"}
{:genres=>["Science Fiction", "Fantasy", "Adventure"], :title=>"Guardians of the Galaxy", :overview=>"Light years from Earth, 26 years after being abducted, Peter Quill finds himself the prime target of a manhunt after discovering an orb wanted by Ronan the Accuser.", :poster_path=>"https://image.tmdb.org/t/p/w185/y31QB9kn3XSudA15tV7UWQ9XLuW.jpg", :release_date=>"2014-08-01"}
{:genres=>["Comedy", "Animation", "Family"], :title=>"Inside Out", :overview=>"Growing up can be a bumpy road, and it's no exception for Riley, who is uprooted from her Midwest life when her father starts a new job in San Francisco. Like all of us, Riley is guided by her emotions - Joy, Fear, Anger, Disgust and Sadness. The emotions live in Headquarters, the control center inside Riley's mind, where they help advise her through everyday life. As Riley and her emotions struggle to adjust to a new life in San Francisco, turmoil ensues in Headquarters. Although Joy, Riley's main and most important emotion, tries to keep things positive, the emotions conflict on how best to navigate a new city, house and school.", :poster_path=>"https://image.tmdb.org/t/p/w185/aAmfIX3TT40zUHGcCKrlOZRKC7u.jpg", :release_date=>"2015-06-19"}
{:genres=>["Fantasy", "Adventure", "Animation", "Family"], :title=>"Spirited Away", :overview=>"Spirited Away is an Oscar winning Japanese animated film about a ten year old girl who wanders away from her parents along a path that leads to a world ruled by strange and unusual monster-like animals. Her parents have been changed into pigs along with others inside a bathhouse full of these creatures. Will she ever see the world how it once was?", :poster_path=>"https://image.tmdb.org/t/p/w185/dL11DBPcRhWWnJcFXl9A07MrqTI.jpg", :release_date=>"2001-07-20"}
{:genres=>["Comedy", "Drama"], :title=>"Life Is Beautiful", :overview=>"A touching story of an Italian book seller of Jewish ancestry who lives in his own little fairy tale. His creative and happy life would come to an abrupt halt when his entire family is deported to a concentration camp during World War II. While locked up he tries to convince his son that the whole thing is just a game.", :poster_path=>"https://image.tmdb.org/t/p/w185/f7DImXDebOs148U4uPjI61iDvaK.jpg", :release_date=>"1997-12-20"}
{:genres=>["Drama"], :title=>"12 Angry Men", :overview=>"The defense and the prosecution have rested and the jury is filing into the jury room to decide if a young Spanish-American is guilty or innocent of murdering his father. What begins as an open and shut case soon becomes a mini-drama of each of the jurors' prejudices and preconceptions about the trial, the accused, and each other.", :poster_path=>"https://image.tmdb.org/t/p/w185/qcL1YfkCxfhsdO6sDDJ0PpzMF9n.jpg", :release_date=>"1957-04-10"}
{:genres=>["Animation", "Family", "Fantasy"], :title=>"Song of the Sea", :overview=>"The story of the last Seal Child’s journey home. After their mother’s disappearance, Ben and Saoirse are sent to live with Granny in the city. When they resolve to return to their home by the sea, their journey becomes a race against time as they are drawn into a world Ben knows only from his mother’s folktales. But this is no bedtime story; these fairy folk have been in our world far too long. It soon becomes clear to Ben that Saoirse is the key to their survival.", :poster_path=>"https://image.tmdb.org/t/p/w185/uvNv23Arf2ZYtimiStSB2c1DAEX.jpg", :release_date=>"2014-09-06"}
{:genres=>["Family", "Animation", "War", "Drama"], :title=>"Grave of the Fireflies", :overview=>"In the latter part of World War II, a boy and his sister, orphaned when their mother is killed in the firebombing of Tokyo, are left to survive on their own in what remains of civilian life in Japan. The plot follows this boy and his sister as they do their best to survive in the Japanese countryside, battling hunger, prejudice, and pride in their own quiet, personal battle.", :poster_path=>"https://image.tmdb.org/t/p/w185/bwVhmPpydv8P7mWfrmL3XVw0MV5.jpg", :release_date=>"1988-04-16"}
{:genres=>["History", "Drama", "Thriller", "War"], :title=>"The Imitation Game", :overview=>"Based on the real life story of legendary cryptanalyst Alan Turing, the film portrays the nail-biting race against time by Turing and his brilliant team of code-breakers at Britain's top-secret Government Code and Cypher School at Bletchley Park, during the darkest days of World War II.", :poster_path=>"https://image.tmdb.org/t/p/w185/noUp0XOqIcmgefRnRZa1nhtRvWO.jpg", :release_date=>"2014-11-14"}
{:genres=>["Drama", "Crime"], :title=>"The Godfather: Part II", :overview=>"The continuing saga of the Corleone crime family tells the story of a young Vito Corleone growing up in Sicily and in 1910s New York; and follows Michael Corleone in the 1950s as he attempts to expand the family business into Las Vegas, Hollywood and Cuba", :poster_path=>"https://image.tmdb.org/t/p/w185/tHbMIIF51rguMNSastqoQwR0sBs.jpg", :release_date=>"1974-12-20"}
{:genres=>["Mystery", "Thriller", "Drama"], :title=>"Gone Girl", :overview=>"With his wife's disappearance having become the focus of an intense media circus, a man sees the spotlight turned on him when it's suspected that he may not be innocent.", :poster_path=>"https://image.tmdb.org/t/p/w185/gdiLTof3rbPDAmPaCf4g6op46bj.jpg", :release_date=>"2014-10-03"}
{:genres=>["Adventure", "Fantasy", "Animation"], :title=>"Princess Mononoke", :overview=>"Ashitaka, a prince of the disappearing Ainu tribe, is cursed by a demonized boar god and must journey to the west to find a cure. Along the way, he encounters San, a young human woman fighting to protect the forest, and Lady Eboshi, who is trying to destroy it. Ashitaka must find a way to bring balance to this conflict.", :poster_path=>"https://image.tmdb.org/t/p/w185/gzlJkVfWV5VEG5xK25cvFGJgkDz.jpg", :release_date=>"1997-07-12"}
